//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace interop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("interop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;botText&quot;: {
        ///        &quot;say&quot;       : &quot;{0}&quot;,
        ///        &quot;join&quot;      : &quot;{0} has joined the chat.&quot;,
        ///        &quot;leave&quot;     : &quot;{0} has disconnected.&quot;,
        ///        &quot;jchan&quot;     : &quot;{0} entered the channel.&quot;,
        ///        &quot;lchan&quot;     : &quot;{0} left the channel.&quot;,
        ///        &quot;kick&quot;      : &quot;{0} has been kicked.&quot;,
        ///        &quot;nick&quot;      : &quot;{0} is now known as {1}.&quot;,
        ///        &quot;crchan&quot;    : &quot;{0} has been created.&quot;,
        ///        &quot;delchan&quot;   : &quot;{0} has been deleted.&quot;,
        ///        &quot;cpwdchan&quot;  : &quot;Password changed successfully.&quot;,
        ///        &quot;cpr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonLang {
            get {
                return ResourceManager.GetString("CommonLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ws://aroltd.com:17777.
        /// </summary>
        internal static string ConnectionAddress {
            get {
                return ResourceManager.GetString("ConnectionAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e25c69c67adfc9e62fcd661b3e825cb3d5357652.
        /// </summary>
        internal static string ConnectionPwd {
            get {
                return ResourceManager.GetString("ConnectionPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to malloc2.
        /// </summary>
        internal static string ConnectionUserDebug {
            get {
                return ResourceManager.GetString("ConnectionUserDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to malloc.
        /// </summary>
        internal static string ConnectionUserRelease {
            get {
                return ResourceManager.GetString("ConnectionUserRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;botText&quot;: {
        ///        &quot;silence&quot;:  &quot;You have been silenced!&quot;,
        ///        &quot;unsil&quot;:    &quot;You have been unsilenced!&quot;,
        ///        &quot;usilok&quot;:   &quot;{0} has been unsilenced.&quot;,
        ///        &quot;silok&quot;:    &quot;{0} has been silenced.&quot;
        ///    },
        ///    &quot;botErrText&quot;: {
        ///        &quot;silerr&quot;:   &quot;Error: User is already silenced!&quot;,
        ///        &quot;usilerr&quot;:  &quot;Error: User is not silenced!&quot;,
        ///        &quot;silperr&quot;:  &quot;Error: You are not allowed to silence this user!&quot;,
        ///        &quot;usilperr&quot;: &quot;Error: You are not allowed to unsilence this user!&quot;,
        ///        &quot;si [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CoreLang {
            get {
                return ResourceManager.GetString("CoreLang", resourceCulture);
            }
        }
    }
}
